stages:
  - build

container-build:
  image: docker:latest
  stage: build
  dependencies: []
  services:
    - docker:dind
  before_script: []
  needs: []
  script:
    - |
      APP_VERSION=$( cat setup.cfg | grep version | cut -d "=" -f 2 | tr -d " " )
      APP_NAME=$( cat setup.cfg | grep name | cut -d "=" -f 2 | tr -d " " )
      echo ${APP_NAME}:${APP_VERSION}
      docker login -u ${CR_USER} -p ${CR_KEY} cr.terradue.com
      docker login -u "$DOCKER_USER" -p "$DOCKER_KEY" index.docker.io
      echo "version: ${APP_VERSION}"
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag="${APP_NAME}:${APP_VERSION}"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = ${tag}"cat
      else
        tag="${APP_NAME}:${APP_VERSION}-$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - |
      docker build -t "cr.terradue.com/ellip-studio/${tag}" --file Dockerfile .
      docker push "cr.terradue.com/ellip-studio/${tag}"
